### ISSUE TITLE
Tips: Perl modules to install on Ubuntu 

### ISSUE THREAD

**Issue by biocyberman** [reineckef/quandico#3]
I had to rerun the installation script `bash install.sh` many times to install the missing modules for quandico. Want to put them up here for future users:

`sudo apt-get install libenv-path-perl libgetopt-long-descriptive-perl libdatetime-perl libtest-script-perl`

**Comment by reineckef** [comment]
Hi @biocyberman. Thanks for this tipp, I have added your line to the README.md.
