### ISSUE TITLE
Can't access sample data on Google drive

### ISSUE THREAD

**Issue by biocyberman** [reineckef/quandico#4]
During installation, I noticed this
```
[ STEP  2c ] Downloading example data ... 

https://googledrive.com/host/0BzLnl09R3GITUDZ0aXFBd2pDR0k:
2016-12-02 12:13:36 ERROR 404: Not Found.
https://googledrive.com/host/0BzLnl09R3GITWU9xTndtZE5iOEE:
2016-12-02 12:13:36 ERROR 404: Not Found.

```

**Comment by reineckef** [comment]
Hello biocyberman,
My apologies! Google has changed the way the URL is resolved. If you click on the file in the browser, you will be redirected. I need to find a way to change the URLs so that these work in scripts as well. In the meantime, I recommended to download these files from the homepage (readme) via a browser.
Thanks,
Frank

**Comment by biocyberman** [comment]
I haven't tested how to overcome the google drive links. You can also try with dropbox instead.

**Comment by reineckef** [comment]
Used `wget "https://drive.google.com/uc?export=download&id=<ID>"` URLs now, which works for text files, but not for BAM because no virus check can be done on the server. Only workaround is browser-based download of these files.

**Comment by biocyberman** [comment]
@reineckef Just noticed you have a @qiagen.com email address, from which I infer you are affiliated with Qiagen. So ask them to host your files or pay for an Amazon cloud service :) 
 (writing before seeing you tag wontfix, but still a suggestion)

**Comment by reineckef** [comment]
That would be more complex than it might seem at first :). I might move them to Dropbox when I have time, but currently it might be just fine for users to download these two files using a browser. Thanks for your suggestion. I hope you get it up and running soon!
